Textured cube + cubemap background.
furotsu/Engine pull request #6
Opened 2022-07-14 14:06 UTC by furotsu

2022-07-16 12:21 UTC, Bonefest requested changes
Ещё я не вижу у тебя использования depth stencil state и вообще depth test. Я даже сначала удивился что это работает) Добавь depth stencil state, условие поставь greater equal, текстуру глубины очищай в 0.

2022-07-16 12:21 UTC, Bonefest commented on Engine/render/renderer.cpp
> +	s_devcon->IASetPrimitiveTopology(D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
Старайся D3D10 вообще не использовать

2022-07-16 12:21 UTC, Bonefest commented on Engine/render/renderer.cpp
> +	TL = XMVector4Transform(TL, camera.m_projInv);
Для камеры лучше дополнительно посчитать и хранить m_projViewInv, чтобы в таких ситуациях избегать умножения на матрицы дважды

2022-07-16 12:21 UTC, Bonefest commented on Engine/render/textureManager.cpp
> +		std::map<const wchar_t*, std::shared_ptr<Texture>>::iterator it = GetInstance()->m_Textures.find(filepath);
Не вижу смысла здесь писать полный тип, тут auto будет более читабельным, т.к все и так понимают какой тип будет

2022-07-16 12:21 UTC, Bonefest commented on Engine/src/camera.cpp
> +		float const h = XMScalarCos((float)0.5 * rad) / XMScalarSin((float)0.5 * rad);
Явный кастинг здесь лишний, добавь просто постфикс f к 0.5

2022-07-16 12:21 UTC, Bonefest commented on Engine/src/camera.cpp
> +		m_viewProjInv = m_projInv * m_viewInv;
А, так ты уже считаешь viewProjInv, тогда просто используй его при расчёте углов

2022-07-16 12:21 UTC, Bonefest commented on Engine/src/controller.cpp
> +				moveCamera(XMVectorSet(0.0f, 0.1f, 0.0f, 0.0f));
Сделай так, чтобы q было движением вниз

2022-07-16 12:21 UTC, Bonefest commented on Engine/src/controller.cpp
> +				moveCamera(XMVectorSet(0.0f, 0.1f, 0.0f, 0.0f));
Причем движением не относительно текущего направления

2022-07-16 12:21 UTC, Bonefest commented on Engine/src/camera.hpp
> +		bool m_updatedBasis = false;
Эти и другие поля не должны быть открытыми, иначе я могу случайно сломать логику или просто запутаться

2022-07-16 20:17 UTC, furotsu commented on Engine/src/camera.hpp
> +		bool m_updatedBasis = false;
++

2022-07-16 20:17 UTC, furotsu commented on Engine/src/controller.cpp
> +				moveCamera(XMVectorSet(0.0f, 0.1f, 0.0f, 0.0f));
++

2022-07-16 20:17 UTC, furotsu commented on Engine/src/camera.cpp
> +		m_viewProjInv = m_projInv * m_viewInv;
++

2022-07-16 20:17 UTC, furotsu commented on Engine/src/camera.cpp
> +		float const h = XMScalarCos((float)0.5 * rad) / XMScalarSin((float)0.5 * rad);
++

2022-07-16 20:17 UTC, furotsu commented on Engine/render/textureManager.cpp
> +		std::map<const wchar_t*, std::shared_ptr<Texture>>::iterator it = GetInstance()->m_Textures.find(filepath);
++

2022-07-16 20:17 UTC, furotsu commented on Engine/render/renderer.cpp
> +	TL = XMVector4Transform(TL, camera.m_projInv);
++

2022-07-16 20:17 UTC, furotsu commented on Engine/render/renderer.cpp
> +	s_devcon->IASetPrimitiveTopology(D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
++

2022-07-19 19:43 UTC, Bonefest commented on Engine/render/renderer.cpp
> +	s_devcon->IASetPrimitiveTopology(D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
Да я до лекции добрался уже после того как ревью сделал) Ну все равно, молодец, что сделал! Лишним не будет

2022-07-19 23:31 UTC, furotsu commented on Engine/render/shaders/cube.hlsl
> +SamplerState objSamplerState;
++

2022-07-19 23:31 UTC, furotsu commented on Engine/render/texture.cpp
> +	s_devcon->PSSetSamplers(0, 1, pTSampleState.access());
++

2022-07-19 23:31 UTC, furotsu commented on Engine/render/renderer.cpp
> +	s_devcon->UpdateSubresource(g_uniformGlobal, 0, NULL, &data, 0, 0);
++

2022-07-19 23:32 UTC, furotsu commented on Engine/src/scene.cpp
> +		renderer.render(skyboxProgram, window, camera, skybox);
++

2022-07-19 23:32 UTC, furotsu commented on Engine/src/controller.cpp
> +		renderer.setPerFrameUniforms(uniform);
++

2022-07-19 23:32 UTC, furotsu commented on Engine/src/controller.cpp
> +		renderer.init();
++

2022-07-19 23:32 UTC, furotsu commented on Engine/render/renderer.hpp
> +		DxResPtr<ID3D11Buffer> g_uniformGlobal;
++

2022-07-19 23:32 UTC, furotsu commented on Engine/src/application.cpp
> +		TextureManager::init();
++

2022-07-20 20:25 UTC, furotsu commented on Engine/src/scene.cpp
> +		window.m_swapchain->Present1(0, 0, &pPresentParameters);
++

2022-07-20 20:25 UTC, furotsu commented on Engine/src/controller.cpp
> +		Globals::GetInstance()->bindSharedSampleState();
++

2022-07-21 19:39 UTC, Bonefest approved these changes

2022-07-25 13:38 UTC, merged