Homework-6
furotsu/Engine pull request #7
Opened 2022-08-02 08:38 UTC by furotsu

Model loader ussing Assimp library

2022-08-02 18:36 UTC, furotsu commented on Engine/src/scene.cpp
>  		window.m_swapchain->Present(0, 0);
++

2022-08-02 18:36 UTC, furotsu commented on Engine/src/window.cpp
++

2022-08-02 18:36 UTC, furotsu commented on Engine/render/instance.cpp
> +namespace engine
++

2022-08-02 18:36 UTC, furotsu commented on Engine/render/instance.cpp
> +		std::vector<Mesh::Triangle> indices;
++

2022-08-02 18:36 UTC, furotsu commented on Engine/src/scene.cpp
> +		models.render();
++

2022-08-02 18:37 UTC, furotsu commented on Engine/render/shaders/modelInstanced.hlsl
> +VSOut VSMain(float3 position : POSITION, float2 texCoord : TEXCOORD, float3 instancePosition : INSTANCEPOS)
++

2022-08-02 18:37 UTC, furotsu commented on Engine/render/shaders/modelInstanced.hlsl
> +	 float4x4 meshMat;
++

2022-08-03 06:55 UTC, Bonefest requested changes
У меня почему-то не грузит диффы с этого проекта. Из-за этого пишу замечания одним сообщением:
1. model.hpp:12 - Не вижу применения `template <typename T>`.
2. Перенеси определение методов IndexBuffer в соурс файл. Иначе это может создать проблемы с компиляцией, например, определений может быть два.
3. model.hpp:120 - meshes не уверен, что это поле должно быть открытым. Но даже если ты добавишь геттер, все равно, нужно подумать над инкапсуляцией полей самого Mesh, т.к мы не должны иметь возможности менять его вершины и треугольники (без влияния на Model).
4. opaque_instances.cpp:86 - Не используй D3D10
5. opaque_instances.cpp:96 - .model() выглядит здесь лишним. Не нужно просто брать и копировать подсказку. Мне кажется, в коде Эмиля он имел ввиду, что model() должен возвращать какую-нибудь структуру, которая также бы содержала меши модели.

2022-08-04 19:57 UTC, furotsu commented
> `MeshSystem::GetInstance()->initOpaqueInstances()` Это не должно вызываться из controller.cpp, это подсистема движка и она после Engine::init должна быть уже инициализирована, делай это в MeshSystem::init

Но тогда же получится, что задавать все шейдеры для OpaqueInstances нужно будет в самом Engine::init. Или там нужно просто добавлять нужное их количество, а шейдеры привязывать в Controller::init?

2022-08-25 06:07 UTC, merged