Homework 7
furotsu/Engine pull request #8
Opened 2022-08-21 23:14 UTC by furotsu

2022-08-24 10:25 UTC, Bonefest requested changes
Сделай окно большего размера, пожалуйста

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSource.hpp
> +		uint32_t position;
Назови, пожалуйста, positionId / idx, т.к это название путает.

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSource.hpp
> +		DirectionalLight(XMVECTOR direction, XMVECTOR color, float power = 1.0f, float solidAngle = 2.0f * G_PI);
Передавай xmvector по ссылке

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSystem.cpp
> +		{
Не советую проверять s_manager каждый раз. Лучше добавь #ifdef DEBUG, а ещё лучше - гарантируй, что такого не произойдет.

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSystem.cpp
> +		s_devcon->VSSetConstantBuffers(1, 1, m_uniformGlobal.access()); // 2 if we use par app buffer
Советую слоты как-то назвать и вынести в отдельный файл. Часто встречается подход, в котором слоты выносят в hlsl.hpp файл - файл, который шерится между шейдерами и cpp и в нем объявляют используя #define все слоты: для cbuffer, для sampler, srv. Из плюсов: код легче читается, номера слотов не нужно запоминать. Из минусов: для больших движков плохо скейлится

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSystem.cpp
> +			pl.properties.irridance = irradianceAtDistanceToRadiance(pl.properties.color * pl.properties.power /10.0f, 1.0f/math::lengthVec3(pl.properties.position - camera.positionVec3()), pl.properties.radi
Что такое 10? Назови его как-нибудь, пожалуйста.

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSystem.cpp
> +	XMFLOAT3 LightSystem::irradianceAtDistanceToRadiance(XMFLOAT3 irradiance, float distance, float radius)
Кстати, мы можем сюда передавать distance * distance - тогда нам не нужно будет считать sqrt(length) на 129 строке. Правда и формулу нужно немного допилить: домножить angleSin на радиус и angleCos отнимать просто angleSin

2022-08-24 10:25 UTC, Bonefest commented on Engine/lightSystem.hpp
> +		void addPointLight(PointLight& pl, std::vector<EmissiveInstances::Instance> instances);
Передавай массивы по константной ссылке

2022-08-24 10:25 UTC, Bonefest commented on Engine/meshSystem.cpp
> +		{
Тоже самое: не проверяй это каждый раз (хотя бы в релизе)

2022-08-24 10:25 UTC, Bonefest commented on Engine/meshSystem.cpp
> +		m_opaqueInstances.push_back(i);
Какая-то недоработанная логика. Зачем нам массив, если ты всегда используешь 0й элемент?

2022-08-24 10:25 UTC, Bonefest commented on Engine/renderTarget.cpp
> +	bool RenderTarget::init(int textureWidth, int textureHeight)
Передавай format в качестве параметра. Или попробуй абстрагировать texture2D и передавать bind flags и usage и создавать также автоматически необходимые view.

2022-08-24 10:25 UTC, Bonefest commented on Engine/shaders/globals.hlsli
> +	float3 pos;
Перепроверь паддинги. Используй float4, если 4й компонент не нужен.

2022-08-24 10:25 UTC, Bonefest commented on Engine/shaders/modelInstanced.hlsl
> +	output.fragPos = mul(float4(input.position, 1.0f), modelMat).xyz;
fragPos не самое удачное имя, т.к fragPos больше про позицию фрагмента в пиксельных координатах. Лучше posWS или что-то в этом духе

2022-08-24 10:25 UTC, Bonefest commented on Engine/shaders/modelInstanced.hlsl
> +	float3 vertexPosition_cameraspace = mul(mul(float4(input.position, 1.0f), modelMat), g_view);
У тебя уже есть значение позиции в мировых координатах, переиспользуй его

2022-08-24 10:25 UTC, Bonefest commented on Engine/shaders/modelInstanced.hlsl
> +		normal = normalize(input.TBN[2]) * 2.0f - 1.0f;
Зачем вектор домножать на 2.0? У нас уже и так вектор в границах [-1, 1]

2022-08-25 11:34 UTC, Bonefest commented
Добавь, пожалуйста, ещё один кубик, но с какой-нибудь другой текстурой (нормали и альбедо) и сделай его так, чтобы он смотрелся хотя бы примерно как в реальной жизни. Можешь взять даже с какого-нибудь туториала типа OpenGL

2022-08-25 11:46 UTC, Bonefest commented
Добавь, пожалуйста, ещё один кубик, но с какой-нибудь другой текстурой (нормали и альбедо) и сделай его так, чтобы он смотрелся хотя бы примерно как в реальной жизни. Можешь взять даже с какого-нибудь туториала типа OpenGL

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSource.hpp
> +		uint32_t position;
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSource.hpp
> +		DirectionalLight(XMVECTOR direction, XMVECTOR color, float power = 1.0f, float solidAngle = 2.0f * G_PI);
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSystem.cpp
> +		{
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSystem.cpp
> +		s_devcon->VSSetConstantBuffers(1, 1, m_uniformGlobal.access()); // 2 if we use par app buffer
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSystem.cpp
> +			pl.properties.irridance = irradianceAtDistanceToRadiance(pl.properties.color * pl.properties.power /10.0f, 1.0f/math::lengthVec3(pl.properties.position - camera.positionVec3()), pl.properties.radi
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSystem.cpp
> +	XMFLOAT3 LightSystem::irradianceAtDistanceToRadiance(XMFLOAT3 irradiance, float distance, float radius)
++

2022-08-25 20:37 UTC, furotsu commented on Engine/lightSystem.hpp
> +		void addPointLight(PointLight& pl, std::vector<EmissiveInstances::Instance> instances);
++

2022-08-25 20:37 UTC, furotsu commented on Engine/meshSystem.cpp
> +		{
++

2022-08-25 20:37 UTC, furotsu commented on Engine/meshSystem.cpp
> +		m_opaqueInstances.push_back(i);
++

2022-08-25 20:37 UTC, furotsu commented on Engine/renderTarget.cpp
> +	bool RenderTarget::init(int textureWidth, int textureHeight)
++

2022-08-25 20:37 UTC, furotsu commented on Engine/shaders/globals.hlsli
> +	float3 pos;
++

2022-08-25 20:37 UTC, furotsu commented on Engine/shaders/modelInstanced.hlsl
> +	output.fragPos = mul(float4(input.position, 1.0f), modelMat).xyz;
++

2022-08-25 20:37 UTC, furotsu commented on Engine/shaders/modelInstanced.hlsl
> +	float3 vertexPosition_cameraspace = mul(mul(float4(input.position, 1.0f), modelMat), g_view);
++

2022-08-25 20:37 UTC, furotsu commented on Engine/shaders/modelInstanced.hlsl
> +		normal = normalize(input.TBN[2]) * 2.0f - 1.0f;
++

2022-08-31 10:52 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float NoL = max(dot(fragNorm, lightSpecDirection), 0.0f) + g_SMALL_OFFSET;
++

2022-08-31 10:54 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	clampDirToHorizon(lightSpecDirection, NoL, fragNorm, 0.0f);
++

2022-08-31 10:54 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float NoV = max(dot(fragNorm, viewDir), 0.0f) + g_SMALL_OFFSET;
++

2022-08-31 10:54 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float NoH = max(dot(fragNorm, halfDir), 0.0f);
++

2022-08-31 10:54 UTC, furotsu commented on Engine/src/main.cpp
> +	LightSystem* LightSystem::s_manager = nullptr;
++

2022-08-31 10:54 UTC, furotsu commented on Engine/shaders/globals.hlsli
> +	PointLight g_pointLight;
++

2022-08-31 10:54 UTC, furotsu commented on Engine/src/scene.hpp
> +		float EV100;
++

2022-08-31 10:54 UTC, furotsu commented on Engine/src/scene.cpp
> +		m_postRenderProgram->bind();
++

2022-08-31 10:54 UTC, furotsu commented on Engine/src/controller.cpp
> +		window.bindTarget(scene.m_pDSV);
++

2022-08-31 10:55 UTC, furotsu commented on Engine/src/scene.hpp
> +		void renderFrame(const Camera& camera);
++

2022-09-08 07:47 UTC, furotsu commented on Engine/src/renderer.cpp
> +		terrain.render();
++

2022-09-08 07:47 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float GnoL = max(dot(geomNormal, lightDir), g_SMALL_OFFSET);
++

2022-09-08 07:47 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float3 spec = CookTorrance_GGX(viewDir, normal, attenuation * (2.0f * g_PI), light.pos, posWS, material.F0, distance, light.radius, rough2);
++

2022-09-08 07:47 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float h = 1.0f - sqrt(1.0f - (radius / distance) * (radius / distance));
++

2022-09-08 07:47 UTC, furotsu commented on Engine/shaders/globals.hlsli
> +static const float g_ROUGHNESS_MULTIPLIER = 10.0f;
++

2022-09-12 13:32 UTC, e-kabirov commented on Engine/src/meshSystem.hpp
> +		SolidVector<EmissiveInstances> m_emissiveInstances;
А зачем делать вектор то? Предполагается, что OpaqueInstances это всё с Opaque шейдером, а EmissiveInstances с Emissive шейдером. Не может быть много одних и тех же шейдеров Opaque или Emissive. Это будут разные шейдеры с разными Instance и/или Uniform данными

2022-09-12 13:52 UTC, e-kabirov commented on Engine/shaders/pbrRes.hlsli
> +	return ((diff + spec) * NoL) * (light.radiance)*fadingMicro* fadingMacro;
Я в чате писал про то, что для более корректной яркости отражения нужно NoL умножение только для диффуза оставить, а деление на NoL внутри min() в CookTorrance убрать, так как отменяются два фактора, а min() портит математику

2022-09-12 14:01 UTC, e-kabirov commented on Engine/shaders/pbrRes.hlsli
> +	float attenuation = light.solidAngle / (2.0f * g_PI);
Я говорил тут не нужно деление на 2PI

2022-09-12 14:14 UTC, e-kabirov commented on Engine/shaders/pbrRes.hlsli
> +	float3 diff = (Fdiff * material.albedo * light.color * solidAngle) / (g_2PI2);
Это что за 2PI^2 ?

2022-09-12 14:25 UTC, e-kabirov commented on Engine/shaders/pbrRes.hlsli
> +	if (rough2 < g_MIN_ROUGHNESS)
Просто = max(rough2, g_MIN_ROUGHNESS)

2022-09-15 07:01 UTC, furotsu commented on Engine/src/meshSystem.hpp
> +		SolidVector<EmissiveInstances> m_emissiveInstances;
++

2022-09-15 07:01 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	return ((diff + spec) * NoL) * (light.radiance)*fadingMicro* fadingMacro;
++

2022-09-15 07:01 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float lightDiameteralSin = sin(solidAngle);
++

2022-09-15 07:02 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float NoL = max(dot(normal, lightDir), 0.0f);
++

2022-09-15 07:02 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float sphereCos = sqrt(1.0f - (radius / distance) * (radius / distance));
++

2022-09-15 07:02 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float3 diff = (Fdiff * material.albedo * light.color * solidAngle) / (g_2PI2);
++

2022-09-15 07:02 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	if (rough2 < g_MIN_ROUGHNESS)
++

2022-09-15 07:02 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float attenuation = light.solidAngle / (2.0f * g_PI);
++

2022-09-15 07:03 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float lightDiameteralSin = sin(solidAngle);
++

2022-09-23 11:03 UTC, merged