Homework 8
furotsu/Engine pull request #9
Opened 2022-09-23 23:49 UTC by furotsu

Image Based Lighting + Shadow Mapping

2022-09-29 09:13 UTC, e-kabirov commented
Сделай источники разноцветные хоть для разнообразия

2022-09-29 11:19 UTC, e-kabirov requested changes

2022-09-29 11:19 UTC, e-kabirov commented on Engine/shaders/shadowMap.hlsl
> +	float g_textureCubePos;
Зачем float?

2022-09-29 11:19 UTC, e-kabirov commented on Engine/src/meshSystem.cpp
> +		for (auto& emmisiveModel : m_emissiveInstances.perModel)
У тебя в LightSystem должны быть перечислены источники света, итерируйся по ним, а не по emissive инстансам.
Emissive меш может и не быть источником света, свет и меши с точки зрения движка - разные несвязанные вещи вообще. Всю эту функцию методом LightSystem можешь сделать

2022-09-29 11:19 UTC, e-kabirov commented on Engine/src/meshSystem.cpp
> +						d.textureCubePos = counter;
Этот цикл со сменой sliceOffset для геометрического шейдера должен быть самым внутренним циклом, там где DrawInstanced, как я говорил, потому что иначе вместо того, чтобы нарисовать все инстансы меша во все кубмапы, ты постоянно переключаешь вертекс буфферы

2022-09-29 11:21 UTC, e-kabirov commented on Engine/src/meshSystem.cpp
> +						shadowMapShader->bindUniforms(data, ShaderType::GEOMETRY);
А если у тебя там массивы буфферов в шейдере, проще просто индекс передавать, какой буффер меняешь

2022-09-29 11:26 UTC, e-kabirov commented
if (instance.name != "terrain")

Такого в движке быть не должно. Ты можешь запомнить ещё в Controller, когда создал пол, TransformID у объекта, и эту логику, что объект является полом, делать, сравнивая TransformID.

И почему transformID называется у тебя transformMatrix? Это сбивает

2022-10-01 11:21 UTC, Bonefest requested changes

2022-10-01 11:21 UTC, Bonefest commented on Engine/shaders/opaque.hlsl
> +	Surface material;
У тебя в коде смешиваются понятия. В целом (не уверен насколько это формально), material является частью surface. Surface - это что-то, что разделяет два медиума. Surface можна описать как геометрический объект, у которого есть некоторые свойства (описываются с помощью материала). В твоём случае, можешь оставить код как есть, но `Surface material;` желательно поменять на `Surface surface;`. Советую глянуть Graphics Codex для доп. деталей.

2022-10-01 11:21 UTC, Bonefest commented on Engine/shaders/opaque.hlsl
> +		float3 lightDir = normalize(g_pointLight[i].pos - input.PosWS);
Старайся не считать что-то дважды. Напиши себе вспомогательную функцию, которая а) Нормализирует вектор б) Возвращает его длину и используй её.

2022-10-01 11:21 UTC, Bonefest commented on Engine/shaders/opaque.hlsl
> +		float3 lightDir = normalize(g_pointLight[i].pos - input.PosWS);
Перенеси lightDir и используй в getPointLightVisibility - это немного повысит читабельность

2022-10-01 11:21 UTC, Bonefest commented on Engine/shaders/opaque.hlsl
> +		//light
Что я должен понять с этого комментария?)

2022-10-01 11:21 UTC, Bonefest commented on Engine/shaders/pbrRes.hlsli
> +	float r = shadowMap.Sample(g_sampler, float4(sampleDir, pointlightIndex)).r;
Не вижу где это применяется

2022-10-01 11:21 UTC, Bonefest commented on Engine/src/renderer.cpp
> +	void Renderer::init(const Window& window, uint32_t pointLightNum)
Функции инициализации могут зафейлиться. Проверь хотя бы через assert. Или можешь возвращать булевые значения и проверять где-то на уровне выше.

2022-10-01 11:21 UTC, Bonefest commented on Engine/src/meshSystem.cpp
> +		shadowMapShader = ShaderManager::GetInstance()->getShader(shaders, ied);
Лучше создай более абстрактный класс, что-то в духе ShadowsSystem, который будет сам отвечать за инициализацию и удаление данных связанных с вычислениями теней. Думай о нём со стороны юзера: "У меня есть "чёрный ящик" (ака ShadowmapSystem), которому я говорю как рисовать и куда, а он мне производит набор теней". Тут могут быть и другие подходы, например, представление в виде пассов, но это будет сложно интегрировать в твою архитектуру.

(Этот комментарий относится и к другим частям кода, связанным с логикой отрисовки теней)

2022-10-03 12:52 UTC, furotsu commented on Engine/shaders/pbrRes.hlsli
> +	float r = shadowMap.Sample(g_sampler, float4(sampleDir, pointlightIndex)).r;
++

2022-10-03 12:52 UTC, furotsu commented on Engine/shaders/opaque.hlsl
> +		float3 lightDir = normalize(g_pointLight[i].pos - input.PosWS);
++

2022-10-03 12:52 UTC, furotsu commented on Engine/shaders/opaque.hlsl
> +	Surface material;
++

2022-10-03 12:52 UTC, furotsu commented on Engine/src/meshSystem.cpp
> +						d.textureCubePos = counter;
++

2022-10-03 12:52 UTC, furotsu commented on Engine/shaders/shadowMap.hlsl
> +	float g_textureCubePos;
++

2022-10-03 12:54 UTC, furotsu commented on Engine/src/renderer.cpp
> +		s_devcon->PSSetShaderResources(SHADOWMAP_RESOURCE_SLOT, 1, &view);
++

2022-10-09 09:35 UTC, e-kabirov commented
Пулл реквест невозможно смотреть, мастер находится на непонятном коммите, который уже после коммитов с заданием стоит, вкладка files в ПР не работает.

Свичнись на мастер, сделай git reset --hard bb52cb25ef58684d65a219a20089f286ca4d5028, чтобы переставить мастер, и запушь мастер с форсом

Там всё как-то намешано с мёрджами...
![image](https://user-images.githubusercontent.com/111517008/194749342-eddb0961-a634-4a61-a632-551661097a6c.png)

2022-10-09 09:38 UTC, e-kabirov commented
Никакого addShadowMapShader не должно быть, в чём смысл делать это public методом? Можно туда любой шейдер запушить? У тебя Opaque/Emissive есть группы, которые определяют, какие инстансы каким материалом рисуются, там всё для рендера же определяется, просто в Opaque добавь шейдер depth-only для теней, в Emissive сейчас не нужно

2022-10-09 09:40 UTC, e-kabirov commented on Engine/src/renderer.cpp
> +	void Renderer::init(const Window& window, uint32_t pointLightNum)
@Bonefest @furotsu не имеет смысла добавлять бульки и попытки проверки успешности инициализации движка, если что-то фейлится, программу уже не спасти, это же не какой-то User Input, просто ассерты

2022-10-09 09:41 UTC, e-kabirov commented on Engine/src/renderer.cpp
> +	void Renderer::init(const Window& window, uint32_t pointLightNum)
А обработку булек вверх по коллстеку двигать - только код усложняет и путает, тут только ассерты нужны

2022-10-09 09:45 UTC, e-kabirov commented on Engine/src/meshSystem.cpp
> +						shadowMapShader->bindUniforms(data, ShaderType::GEOMETRY);
Не исправлено?

2022-10-09 09:50 UTC, e-kabirov commented
[maxvertexcount(18 * g_MAX_POINT_LIGHTS)]
У тебя всё тут было нормально! Не надо в геом шейдере писать 18*g_MAX_POINT_LIGHTS.
Там есть ограничение на макс число вершин и общее макс число аттрибутов, которые стримятся из геом шейдера, верни как было.
А g_textureCubePos ты должен был оставить как униформу, которая внутри самого вложенного цикла в C++ меняется, чтобы по очереди в каждую кубмапу инстанцированно нарисовать меши

2022-10-16 05:47 UTC, Bonefest requested changes
Ещё заметил что файл shadowSystem.cpp немного в странном месте лежит, не забудь перенести его в положенное место

2022-10-16 05:47 UTC, Bonefest commented on Engine/shaders/shadowMap.hlsl
> +	float g_textureCubePos;
Ты это не исправил

2022-10-16 05:47 UTC, Bonefest commented on Engine/shadowSystem.cpp
> +	void ShadowSystem::renderToShadowMap(uint32_t shadowMapIndex, const Camera& camera, Window& window)
Не вижу причин вообще сюда передавать Window. Viewport не только с RTV связан, которые на экран рисуются. Сейчас это выглядит как лишняя зависимость.

2022-10-16 05:47 UTC, Bonefest commented on Engine/src/actor/emissive_instances.cpp
> +				struct vertexCbuffer
Насколько я понял, ты используешь (хоть и неявно) это объявление несколько раз в коде (как минимум, ещё при выделении памяти). Это повторение кода, не понятно почему ты такой дизайн выбрал. Вынеси определения в начало файла, в отдельный namespace (анонимный), если уверен, что больше эта структура нигде не нужна.

2022-10-16 05:47 UTC, Bonefest commented on Engine/src/actor/emissive_instances.cpp
> +					struct pixelCbuffer
Здесь такая же ситуация, как и выше

2022-10-16 05:47 UTC, Bonefest commented on Engine/src/render/opaque_instances.cpp
> +				struct vertexCbuffer
Такая же ситуация, как в emissive_instances.cpp

2022-10-17 08:42 UTC, e-kabirov commented on Engine/src/meshSystem.cpp
> +						shadowMapShader->bindUniforms(data, ShaderType::GEOMETRY);
++

2022-10-17 08:48 UTC, e-kabirov commented on Engine/src/controller.cpp
> +		MeshSystem::GetInstance()->addOpaqueInstance(shadersOpaque, iedOpaque, shadersShadowMap, iedShadowMap);
Раньше я этого не замечал, но почему у тебя инициализация MeshSystem::XXXInstances происходит внутри контроллера, а не при инициализации движка, и называются addXXXInstance?

2022-10-17 21:20 UTC, furotsu commented on Engine/src/controller.cpp
> +		MeshSystem::GetInstance()->addOpaqueInstance(shadersOpaque, iedOpaque, shadersShadowMap, iedShadowMap);
++

2022-10-17 21:20 UTC, furotsu commented on Engine/src/render/opaque_instances.cpp
> +				struct vertexCbuffer
++

2022-10-17 21:20 UTC, furotsu commented on Engine/src/actor/emissive_instances.cpp
> +					struct pixelCbuffer
++

2022-10-17 21:20 UTC, furotsu commented on Engine/src/actor/emissive_instances.cpp
> +				struct vertexCbuffer
++

2022-10-17 21:20 UTC, furotsu commented on Engine/shadowSystem.cpp
> +	void ShadowSystem::renderToShadowMap(uint32_t shadowMapIndex, const Camera& camera, Window& window)
++

2022-10-17 21:20 UTC, furotsu commented on Engine/src/meshSystem.cpp
> +		shadowMapShader = ShaderManager::GetInstance()->getShader(shaders, ied);
++

2022-10-17 21:21 UTC, furotsu commented on Engine/src/renderer.cpp
> +	void Renderer::init(const Window& window, uint32_t pointLightNum)
++

2022-10-17 21:21 UTC, furotsu commented on Engine/shaders/shadowMap.hlsl
> +	float g_textureCubePos;
++

2022-10-29 19:51 UTC, Bonefest approved these changes

2022-12-19 15:38 UTC, merged